 [xTrain, tTrain, xValid, tValid, xTest, tTest] = LoadCIFAR(3);
  %imshow(xTrain(:,:,:,25081))
  labelCount = length(tTrain)
  layers = [
    imageInputLayer([32 32 3])
    fullyConnectedLayer(50)
    reluLayer
    fullyConnectedLayer(50)
    reluLayer
    fullyConnectedLayer(10)
    softmaxLayer
    classificationLayer
    ];

options = trainingOptions(...
'sgdm',...
'Momentum',0.9,...
'MaxEpochs',400,...
'MiniBatchSize',8192,...
'InitialLearnRate',0.001,...
'Shuffle','every-epoch',...
'ValidationPatience',3,...
'ValidationFrequency',30,...
'ValidationData',{xValid,tValid},...
'Plots','Training-Progress');

net = trainNetwork(xTrain,tTrain,layers,options);
%Epochs: 210, Classification Error: 0.5128
%
 [xTrain, tTrain, xValid, tValid, xTest, tTest] = LoadCIFAR(3);
  labelCount = length(tTrain)
  layers = [
    imageInputLayer([32 32 3])
    fullyConnectedLayer(50)
    reluLayer
    fullyConnectedLayer(50)
    reluLayer
    fullyConnectedLayer(50)
    reluLayer

    fullyConnectedLayer(10)
    softmaxLayer
    classificationLayer
    ];

options = trainingOptions(...
'sgdm',...
'Momentum',0.9,...
'MaxEpochs',400,...
'MiniBatchSize',8192,...
'InitialLearnRate',0.003,...
'Shuffle','every-epoch',...
'ValidationPatience',3,...
'ValidationFrequency',30,...
'ValidationData',{xValid,tValid},...
'Plots','Training-Progress');

net = trainNetwork(xTrain,tTrain,layers,options);
outputs = net.classify(xTest);
classification_error(outputs,tTest);
%158,  0.5237
 [xTrain, tTrain, xValid, tValid, xTest, tTest] = LoadCIFAR(3);
  %imshow(xTrain(:,:,:,25081))
  labelCount = length(tTrain)
  layers = [
    imageInputLayer([32 32 3])
    fullyConnectedLayer(50)
    reluLayer
    fullyConnectedLayer(50)
    reluLayer
    fullyConnectedLayer(10)
    softmaxLayer
    classificationLayer
    ];

options = trainingOptions(...
'sgdm',...
'Momentum',0.9,...
'MaxEpochs',400,...
'MiniBatchSize',8192,...
'InitialLearnRate',0.001,...
'Shuffle','every-epoch',...
'ValidationPatience',3,...
'ValidationFrequency',30,...
'ValidationData',{xValid,tValid},...
'Plots','Training-Progress',...
'L2Regularization',0.2);

net = trainNetwork(xTrain,tTrain,layers,options);

%Epochs: 375, Classification Error: 0.4924

 [xTrain, tTrain, xValid, tValid, xTest, tTest] = LoadCIFAR(4);
  %imshow(xTrain(:,:,:,25081))
  labelCount = length(tTrain)
  layers = [
    imageInputLayer([32 32 3])
    convolution2dLayer(5,20,'Padding',1, 'Stride',1)
    reluLayer
    maxPooling2dLayer(2,'Padding',0,'Stride',2)
    fullyConnectedLayer(50)
    reluLayer
    fullyConnectedLayer(10)
    reluLayer
    softmaxLayer
    classificationLayer
    ];

options = trainingOptions(...
'sgdm',...
'Momentum',0.9,...
'MaxEpochs',120,...
'MiniBatchSize',8192,...
'InitialLearnRate',0.001,...
'Shuffle','every-epoch',...
'ValidationData',{xValid,tValid},...
'ValidationPatience',3,...
'ValidationFrequency',30,...
'Plots','Training-Progress');

net = trainNetwork(xTrain,tTrain,layers,options);

%Epochs: 120
%tTrain: 0.3365
%tValid: 0.3980
%tTest: 0.3925

 [xTrain, tTrain, xValid, tValid, xTest, tTest] = LoadCIFAR(4);
  %imshow(xTrain(:,:,:,25081))
  labelCount = length(tTrain)
  layers = [
    imageInputLayer([32 32 3])
    convolution2dLayer(3,20,'Padding',1, 'Stride',1)
    batchNormalizationLayer
    reluLayer
    maxPooling2dLayer(2,'Padding',0,'Stride',2)
    convolution2dLayer(3,30,'Padding',1, 'Stride',1)
    batchNormalizationLayer
    reluLayer
    maxPooling2dLayer(2,'Padding',0,'Stride',2)
    convolution2dLayer(3,50,'Padding',1, 'Stride',1)
    batchNormalizationLayer
    reluLayer
    fullyConnectedLayer(10)
    softmaxLayer
    classificationLayer
    ];

options = trainingOptions(...
'sgdm',...
'Momentum',0.9,...
'MaxEpochs',120,...
'MiniBatchSize',8192,...
'InitialLearnRate',0.001,...
'Shuffle','every-epoch',...
'ValidationData',{xValid,tValid},...
'ValidationPatience',3,...
'ValidationFrequency',30,...
'Plots','Training-Progress');

net = trainNetwork(xTrain,tTrain,layers,options);

%Epochs: 120
%tTrain: 0.2698
%tValid: 0.3069
%tTest: 0.3043